### PR TITLE
Update dependencies to fix authentication error and use latest jackson.

### PR DESCRIPTION
**Pull request by tim93422**
Update spring-social-facebook and jackson versions to fix authentication error in issue #6.

### CODE REVIEW

**Comment by tim93422** [comment]
The build failed -- but due to rake not being configured, not the content of the submission.

**Comment by dougforester** [comment]
Newbie here. Is there something I am supposed to do to fix this problem? Or to see a fix?
Thanks.

**Comment by gregturn** [comment]
Actually, Spring Social Facebook is on 2.0.1.RELEASE, so I have updated it suitably to work with that.

**Comment by tim93422** [comment]
that is even better! Thanks.

**Pull request closed without merging**
